# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
# For more information, see: https://github.com/actions/stale

name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '23 13 * * *'  # Läuft täglich um 23:13 UTC
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Mark stale issues and PRs
        uses: actions/stale@v9
        with:
          stale-issue-message: "This issue has been marked as stale due to inactivity. It will be closed in 7 days if no further activity occurs."
          stale-pr-message: "This pull request has been marked as stale due to inactivity. It will be closed in 7 days if no further activity occurs."
          close-issue-message: "This issue has been closed due to inactivity. If you still need this, feel free to reopen it."
          close-pr-message: "This PR has been closed due to inactivity. Feel free to open a new one if needed."
          stale-issue-label: "no-issue-activity"
          stale-pr-label: "no-pr-activity"
          days-before-stale: 30  # Markiere als stale nach 30 Tagen Inaktivität
          days-before-close: 7   # Schließe nach 7 Tagen, falls keine Aktivität mehr erfolgt
